using Microsoft.ML;
using static ITAdministrationApp.Models.TicketClassification;
using System;
using System.Collections.Generic;
using System.IO;

namespace ITAdministrationApp.Services
{
    public class TicketClassificationService
    {
        private readonly MLContext _mlContext;
        private ITransformer _model;

        public TicketClassificationService()
        {
            _mlContext = new MLContext();
        }

        public void TrainModel()
        {
            // Create a static dataset for training
            var descriptions = new List<TicketDescription>
            {
                new TicketDescription { Description = "System crash when opening software", Label = "Critical" },
                new TicketDescription { Description = "Unable to connect to VPN", Label = "Network Issue" },
                new TicketDescription { Description = "Printer not working", Label = "Hardware Issue" },
                new TicketDescription { Description = "Forgot password", Label = "Authentication Issue" },
                new TicketDescription { Description = "Software update required", Label = "Software Issue" },
                new TicketDescription { Description = "Hospital-wide electronic medical records system unavailable during morning rounds", Label = "Critical" },
                new TicketDescription { Description = "Primary CAD system down in County Emergency Center - fails over to backup", Label = "Critical" },
                new TicketDescription { Description = "Statewide system unresponsive during early voting period", Label = "Critical" },
                new TicketDescription { Description = "Cell door controls and cameras offline at State Penitentiary", Label = "Critical" },
                new TicketDescription { Description = "ERP system not responding, affecting all departments", Label = "Critical" },
                new TicketDescription { Description = "System detected multiple login attempts from unknown IP", Label = "Security Incident" },
                new TicketDescription { Description = "Employee received a phishing email requesting credentials", Label = "Security Incident" },
                new TicketDescription { Description = "Detected unauthorized software running on the server", Label = "Security Incident" },
                new TicketDescription { Description = "Firewall logs show continuous attack attempts from foreign IPs", Label = "Security Incident" },
                new TicketDescription { Description = "PC locked by unknown ransomware demanding Bitcoin", Label = "Security Incident" },
                new TicketDescription { Description = "The printer isn't working", Label = "Hardware Issue" },
                new TicketDescription { Description = "Printer is stuck with a paper jam error", Label = "Hardware Issue" },
                new TicketDescription { Description = "User reported that their wireless mouse is not responding", Label = "Hardware Issue" },
                new TicketDescription { Description = "Some keys on the keyboard are not functioning properly", Label = "Hardware Issue" },
                new TicketDescription { Description = "Laptop USB ports are not detecting any devices", Label = "Hardware Issue" },
                new TicketDescription { Description = "User unable to connect to VPN from home", Label = "Network Issue" },
                new TicketDescription { Description = "Sudden increase in network activity at midnight", Label = "Network Issue" },
                new TicketDescription { Description = "User laptop keeps disconnecting from Wi-Fi network", Label = "Network Issue" },
                new TicketDescription { Description = "Network speed is significantly slower in certain areas", Label = "Network Issue" },
                new TicketDescription { Description = "Dormitory Wi-Fi offline", Label = "Network Issue" },
                new TicketDescription { Description = "The accounting software crashes when generating reports", Label = "Software Issue" },
                new TicketDescription { Description = "Outlook is not syncing emails properly", Label = "Software Issue" },
                new TicketDescription { Description = "Excel is freezing when opening large files", Label = "Software Issue" },
                new TicketDescription { Description = "Zoom virtual background not working", Label = "Software Issue" },
                new TicketDescription { Description = "MATLAB license server down", Label = "Software Issue" },
                new TicketDescription { Description = "User forgot their password and needs a reset", Label = "Authentication Issue" },
                new TicketDescription { Description = "Unable to access Outlook - account locked after multiple failed attempts", Label = "Authentication Issue" },
                new TicketDescription { Description = "SSO failure for HR software", Label = "Authentication Issue" },
                new TicketDescription { Description = "Two-factor authentication not working", Label = "Authentication Issue" },
                new TicketDescription { Description = "Student forgot the password for the student portal", Label = "Authentication Issue" },
                new TicketDescription { Description = "Wrong patient records displayed", Label = "Data Error" },
                new TicketDescription { Description = "Duplicate student records", Label = "Data Error" },
                new TicketDescription { Description = "Gradebook not syncing with SIS", Label = "Data Sync Issue" },
                new TicketDescription { Description = "Main database is corrupt, causing application failures", Label = "Data Issue" },
                new TicketDescription { Description = "Accidentally deleted important client proposal from shared drive", Label = "Data Issue" },
                new TicketDescription { Description = "The laptop takes too long to boot and lags when opening files", Label = "Hardware Issue" },
                new TicketDescription { Description = "User experiencing slow internet speeds on workstation", Label = "Network Issue" },
                new TicketDescription { Description = "Laptop takes more than 5 minutes to start", Label = "Hardware Issue" },
                new TicketDescription { Description = "User reports slow response times from helpdesk", Label = "Performance Issue" },
                new TicketDescription { Description = "Slow loading of video lectures", Label = "Software Issue" },
                new TicketDescription { Description = "Audit logs missing for 48 hours", Label = "Data Issue" },
                new TicketDescription { Description = "Missing alt text audit failure", Label = "Compliance Issue" },
                new TicketDescription { Description = "Website SSL certificate expired", Label = "Critical" },
                new TicketDescription { Description = "IRB protocol system login loop", Label = "Software Issue" },
                new TicketDescription { Description = "OFAC screening false positives", Label = "Compliance Issue" },
                new TicketDescription { Description = "Office projector is not displaying output", Label = "Hardware Issue" },
                new TicketDescription { Description = "Microphone feedback in auditorium", Label = "Hardware Issue" },
                new TicketDescription { Description = "Smart classroom projector frozen", Label = "Hardware Issue" },
                new TicketDescription { Description = "Projector bulb is dim and needs replacement", Label = "Hardware Issue" },
                new TicketDescription { Description = "Video interpreter kiosks not connecting to service", Label = "Software Issue" },
                new TicketDescription { Description = "Mobile key not unlocking door", Label = "Software Issue" },
                new TicketDescription { Description = "Campus app crashes immediately on Android devices", Label = "Software Issue" },
                new TicketDescription { Description = "iOS app stuck on login screen after update", Label = "Software Issue" },
                new TicketDescription { Description = "Remote desktop connection issues", Label = "Software Work" },
                new TicketDescription { Description = "VPN disconnects every 15 minutes during remote lectures", Label = "Network Issue" },
                new TicketDescription { Description = "Cannot access the S:\\Marketing folder - permission denied error", Label = "Access Issue" },
                new TicketDescription { Description = "User cannot access shared network drive", Label = "Access Issue" },
                new TicketDescription { Description = "SharePoint access denied", Label = "Access Issue" },
                new TicketDescription { Description = "Intranet website not loading for some employees", Label = "Access Issue" },
                new TicketDescription { Description = "Student cannot access the class materials on the online portal", Label = "Access Issue" },
                new TicketDescription { Description = "Emergency alert system test failure", Label = "Security Incident" },
                new TicketDescription { Description = "Building security camera feeds are not available", Label = "Security Incident" },
                new TicketDescription { Description = "Employee key card not working on main entrance", Label = "Software Issue" },
                new TicketDescription { Description = "Critical temperature warning in data center", Label = "Facilities" },
                new TicketDescription { Description = "Power surge caused multiple workstations to shut down", Label = "Facilities" },
                new TicketDescription { Description = "User requests installation of Microsoft Office", Label = "User Request" },
                new TicketDescription { Description = "User requested Windows updates for their laptop", Label = "User Request" },
                new TicketDescription { Description = "User requests an update for Adobe Acrobat", Label = "User Request" },
                new TicketDescription { Description = "User requested installation of Microsoft Office", Label = "User Request" },
                new TicketDescription { Description = "Need full workstation setup for new hire starting Monday", Label = "User Request" },
                new TicketDescription { Description = "Zero-day vulnerability detected", Label = "Critical" },
                new TicketDescription { Description = "SOC2 audit log gaps", Label = "Compliance" },
                new TicketDescription { Description = "Unauthorized GitHub repo access", Label = "Security Incident" },
                new TicketDescription { Description = "DLP alert: Source code leaked", Label = "Security Incident" },
                new TicketDescription { Description = "Phishing attack on employees", Label = "Security Incident" },
                new TicketDescription { Description = "Jira/Slack integration broken", Label = "Software Issue" },
                new TicketDescription { Description = "SSO failure for HR software", Label = "Authentication" },
                new TicketDescription { Description = "BI dashboard showing stale data", Label = "Data Issue" },
                new TicketDescription { Description = "CRM duplicate contact creation", Label = "Data Issue" },
                new TicketDescription { Description = "Password manager outage", Label = "Security Incident" },
                new TicketDescription { Description = "AWS/Azure region outage", Label = "Critical" },
                new TicketDescription { Description = "Kubernetes pod crash loop", Label = "DevOps" },
                new TicketDescription { Description = "VPN throughput too slow for devs", Label = "Network Issue" },
                new TicketDescription { Description = "SAN storage at 99% capacity", Label = "Hardware Issue" },
                new TicketDescription { Description = "DNS misroute taking down services", Label = "Network Issue" },
                new TicketDescription { Description = "Git repository corruption", Label = "Critical" },
                new TicketDescription { Description = "CI/CD pipeline broken", Label = "DevOps " },
                new TicketDescription { Description = "Production database restore failed", Label = "Disaster Recovery" },
                new TicketDescription { Description = "API rate limit misconfiguration", Label = "Performance" },
                new TicketDescription { Description = "Container registry authentication failure", Label = "Security" },
                new TicketDescription { Description = "Visitor management system offline", Label = "Security" },
                new TicketDescription { Description = "Emergency alert system test failure", Label = "Critical" },
                new TicketDescription { Description = "Cafeteria POS system hacked", Label = "Security Incident" },
                new TicketDescription { Description = "Surveillance camera feed loss", Label = "Monitoring" },
                new TicketDescription { Description = "Fire drill system false alarm", Label = "Safety" },
                new TicketDescription { Description = "Parent portal attendance data wrong", Label = "Data Error" },
                new TicketDescription { Description = "Lunch balance payments not processing", Label = "Payment Issue" },
                new TicketDescription { Description = "Bus tracking app showing wrong routes", Label = "Transportation" },
                new TicketDescription { Description = "Report cards not visible to parents", Label = "Access Issue" },
                new TicketDescription { Description = "Two-way messaging app down", Label = "Communication" },
                new TicketDescription { Description = "Smartboard touch unresponsive", Label = "Hardware Issue" },
                new TicketDescription { Description = "Student tablets not charging", Label = "Device Management" },
                new TicketDescription { Description = "Science probe sensors not connecting", Label = "STEM Lab" },
                new TicketDescription { Description = "Reading app login failure", Label = "EdTech Issue" },
                new TicketDescription { Description = "School bell system stuck looping", Label = "Facilities IT" },
                new TicketDescription { Description = "Payroll system holiday pay error", Label = "HR Issue" },
                new TicketDescription { Description = "Faculty activity reporting tool bug", Label = "Workflow Issue" },
                new TicketDescription { Description = "Donor management CRM data corruption", Label = "Data Loss" },
                new TicketDescription { Description = "Accreditation report generation failed", Label = "Compliance" },
                new TicketDescription { Description = "Event scheduling system double-booking", Label = "Calendar Issue" },
                new TicketDescription { Description = "HPC cluster job scheduler crash", Label = "Critical" },
                new TicketDescription { Description = "Research data storage quota exceeded", Label = "Storage Issue" },
                new TicketDescription { Description = "MATLAB license server down", Label = "License Issue" },
                new TicketDescription { Description = "Genomics software segmentation fault", Label = "Research Software" },
                new TicketDescription { Description = "IRB protocol system login loop", Label = "Compliance Issue" },
                new TicketDescription { Description = "Dormitory Wi-Fi offline", Label = "Network Issue" },
                new TicketDescription { Description = "Lab computers infected with malware", Label = "Security Incident" },
                new TicketDescription { Description = "Smart classroom projector frozen", Label = "AV Support" },
                new TicketDescription { Description = "Library printer jammed", Label = "Hardware Issue" },
                new TicketDescription { Description = "ID card access system failure", Label = "Security Issue" },
                new TicketDescription { Description = "Incorrect GPA calculation", Label = "Data Error" },
                new TicketDescription { Description = "Class registration system crash", Label = "Critical" },
                new TicketDescription { Description = "Financial aid portal rejecting documents", Label = "Workflow Issue" },
                new TicketDescription { Description = "Duplicate student records", Label = "Data Integrity" },
                new TicketDescription { Description = "Transcript generation failed", Label = "Reporting Issue" },
                new TicketDescription { Description = "Blackboard/Canvas login failure during exams", Label = "Critical" },
                new TicketDescription { Description = "Assignment submission portal timeout", Label = "Performance Issue" },
                new TicketDescription { Description = "Gradebook not syncing with SIS", Label = "Data Sync Issue" },
                new TicketDescription { Description = "Lecture capture videos missing", Label = "AV Support" },
                new TicketDescription { Description = "Plagiarism tool (Turnitin) API down", Label = "Integration Issue" },
                new TicketDescription { Description = "Azure cloud outage affecting dispatch & EMR", Label = "Critical" },
                new TicketDescription { Description = "VPN unable to handle ambulance telemetry + EHR access", Label = "Bandwidth Issue" },
                new TicketDescription { Description = "Power outage at data center hosting TMS & PACS", Label = "Disaster Recovery" },
                new TicketDescription { Description = "SD-WAN failure disrupting logistics & telehealth", Label = "Network Outage" },
                new TicketDescription { Description = "Ransomware attack on shared accounting systems", Label = "Security Incident" },
                new TicketDescription { Description = "OR scheduling system double-booking", Label = "Surgical Workflow" },
                new TicketDescription { Description = "Pharmacy robot dispensing errors", Label = "Medication Risk" },
                new TicketDescription { Description = "Staff panic button not alerting security", Label = "Safety Failure" },
                new TicketDescription { Description = "Biometric timeclock misidentifying staff", Label = "Payroll Issue" },
                new TicketDescription { Description = "Blood bank temperature monitoring offline", Label = "Critical" },
                new TicketDescription { Description = "OR scheduling system double-booking", Label = "Surgical Workflow" },
                new TicketDescription { Description = "Pharmacy robot dispensing errors", Label = "Medication Risk" },
                new TicketDescription { Description = "Staff panic button not alerting security", Label = "Safety Failure" },
                new TicketDescription { Description = "Biometric timeclock misidentifying staff", Label = "Payroll Issue" },
                new TicketDescription { Description = "Blood bank temperature monitoring offline", Label = "Critical" },
                new TicketDescription { Description = "Unauthorized access to PHI detected", Label = "HIPAA Breach" },
                new TicketDescription { Description = "Audit logs missing for 48 hours", Label = "Compliance Failure" },
                new TicketDescription { Description = "Encrypted USB drive with patient data lost", Label = "Security Incident" },
                new TicketDescription { Description = "Two-factor authentication bypassed", Label = "Access Control" },
                new TicketDescription { Description = "Ransomware attack on imaging archive", Label = "Disaster Recovery" },
                new TicketDescription { Description = "MRI machine DICOM image transfer stalled", Label = "Radiology Issue" },
                new TicketDescription { Description = "Ventilator alarm not logging to central station", Label = "Critical Alert" },
                new TicketDescription { Description = "Smart bed pressure sensors offline", Label = "Patient Safety" },
                new TicketDescription { Description = "Lab analyzer LIS interface down", Label = "Lab Operations" },
                new TicketDescription { Description = "Anesthesia machine software glitch", Label = "Risk Event" },
                new TicketDescription { Description = "Video consult freezing for rural patients", Label = "Care Delivery" },
                new TicketDescription { Description = "Remote patient monitoring data gaps", Label = "IoT Issue" },
                new TicketDescription { Description = "Telemedicine platform authentication loop", Label = "Access Issue" },
                new TicketDescription { Description = "Wearable health device sync failures", Label = "Data Integrity" },
                new TicketDescription { Description = "ePrescription transmission errors", Label = "Pharmacy Issue" },
                new TicketDescription { Description = "EMR (Epic/Cerner) downtime during rounds", Label = "Critical" },
                new TicketDescription { Description = "Medication barcode scanner not reading", Label = "Patient Safety" },
                new TicketDescription { Description = "Wrong patient records displayed", Label = "HIPAA Violation" },
                new TicketDescription { Description = "Nurse call system unresponsive", Label = "Critical" },
                new TicketDescription { Description = "IV pump firmware update failed", Label = "Medical Device Issue" },
                new TicketDescription { Description = "Invoice generation delays due to TMS crash", Label = "Billing Issue" },
                new TicketDescription { Description = "IFTA tax calculation errors", Label = "Compliance Issue" },
                new TicketDescription { Description = "Dispatcher console freezing during peak", Label = "Performance Issue" },
                new TicketDescription { Description = "Customer portal load tracking outdated", Label = "Customer Experience" },
                new TicketDescription { Description = "Carrier onboarding document upload failures", Label = "Workflow Issue" },
                new TicketDescription { Description = "Dashcam footage corrupted after incident", Label = "Evidence Loss" },
                new TicketDescription { Description = "Driver fatigue alerts false positives", Label = "AI Monitoring Issue" },
                new TicketDescription { Description = "Training portal login failures", Label = "Authentication Issue" },
                new TicketDescription { Description = "Drug testing compliance reports incomplete", Label = "Regulatory Issue" },
                new TicketDescription { Description = "Hazardous material placard generator bug", Label = "Safety Risk" },
                new TicketDescription { Description = "Dashcam footage corrupted after incident", Label = "Evidence Loss" },
                new TicketDescription { Description = "Driver fatigue alerts false positives", Label = "AI Monitoring Issue" },
                new TicketDescription { Description = "Training portal login failures", Label = "Authentication Issue" },
                new TicketDescription { Description = "Drug testing compliance reports incomplete", Label = "Regulatory Issue" },
                new TicketDescription { Description = "Hazardous material placard generator bug", Label = "Safety Risk" },
                new TicketDescription { Description = "Preventive maintenance alerts not triggering", Label = "Compliance Risk" },
                new TicketDescription { Description = "Diagnostic tool unable to read truck ECU", Label = "Hardware Issue" },
                new TicketDescription { Description = "Wheel sensor calibration errors", Label = "Safety Issue" },
                new TicketDescription { Description = "Brake performance data gaps", Label = "Telematics Gap" },
                new TicketDescription { Description = "Oil sample analysis not syncing to system", Label = "Data Issue" },
                new TicketDescription { Description = "Preventive maintenance alerts not triggering", Label = "Compliance Risk" },
                new TicketDescription { Description = "Diagnostic tool unable to read truck ECU", Label = "Hardware Issue" },
                new TicketDescription { Description = "Wheel sensor calibration errors", Label = "Safety Issue" },
                new TicketDescription { Description = "Brake performance data gaps", Label = "Telematics Gap" },
                new TicketDescription { Description = "Oil sample analysis not syncing to system", Label = "Data Issue" },
                new TicketDescription { Description = "Preventive maintenance alerts not triggering", Label = "Compliance Risk" },
                new TicketDescription { Description = "Diagnostic tool unable to read truck ECU", Label = "Hardware Issue" },
                new TicketDescription { Description = "Wheel sensor calibration errors", Label = "Safety Issue" },
                new TicketDescription { Description = "Brake performance data gaps", Label = "Telematics Gap" },
                new TicketDescription { Description = "Oil sample analysis not syncing to system", Label = "Data Issue" },
                new TicketDescription { Description = "Route optimization software suggesting impassable roads", Label = "Routing Error" },
                new TicketDescription { Description = "Load board API connection down", Label = "Integration Issue" },
                new TicketDescription { Description = "Proof-of-delivery signatures not uploading", Label = "Data Sync Issue" },
                new TicketDescription { Description = "Warehouse dock door assignment conflicts", Label = "Yard Management" },
                new TicketDescription { Description = "Temperature alerts for reefer trailers missing", Label = "Cold Chain Issue" },
                new TicketDescription { Description = "GPS tracking offline for 20+ trucks", Label = "Critical" },
                new TicketDescription { Description = "ELD (Electronic Logging Device) compliance errors", Label = "FMCSA Violation" },
                new TicketDescription { Description = "Fuel card transaction failures", Label = "Payment Issue" },
                new TicketDescription { Description = "Engine fault codes not transmitting", Label = "Telematics Issue" },
                new TicketDescription { Description = "Driver app crashing during HOS checks", Label = "Mobile App Issue" },
                new TicketDescription { Description = "New employee login not provisioned", Label = "Onboarding Issue" },
                new TicketDescription { Description = "Training videos not loading", Label = "HR System Issue" },
                new TicketDescription { Description = "Payroll system holiday pay errors", Label = "Payroll Issue" },
                new TicketDescription { Description = "Occupancy report missing data", Label = "Reporting Issue" },
                new TicketDescription { Description = "RevPAR calculations incorrect", Label = "Revenue Issue" },
                new TicketDescription { Description = "Sales mix report corrupted", Label = "Reporting Issue" },
                new TicketDescription { Description = "Server sales tracking discrepancies", Label = "Payroll Issue" },
                new TicketDescription { Description = "Spoilage report overcounting", Label = "Inventory Issue" },
                new TicketDescription { Description = "Customer traffic heatmap offline", Label = "Analytics Issue" },
                new TicketDescription { Description = "TripAdvisor review sync failed", Label = "Reputation Issue" },
                new TicketDescription { Description = "Airbnb calendar not updating", Label = "Integration Issue" },
                new TicketDescription { Description = "Uber Eats orders not printing", Label = "Revenue Loss" },
                new TicketDescription { Description = "OpenTable reservations missing", Label = "Integration Issue" },
                new TicketDescription { Description = "Instacart shopper app crashes", Label = "Third-Party Issue" },
                new TicketDescription { Description = "EBT/SNAP payment processing down", Label = "Critical" },
                new TicketDescription { Description = "Key card printer jammed", Label = "Hardware Issue" },
                new TicketDescription { Description = "Bell cart charging station broken", Label = "Facilities Issue" },
                new TicketDescription { Description = "Kitchen printer offline", Label = "Critical" },
                new TicketDescription { Description = "Handheld POS battery drain", Label = "Hardware Issue" },
                new TicketDescription { Description = "Barcode scanner unresponsive", Label = "Hardware Issue" },
                new TicketDescription { Description = "Freezer temperature alarms", Label = "IoT Alert" },
                new TicketDescription { Description = "PCI-DSS compliance scanner alerts", Label = "Security Issue" },
                new TicketDescription { Description = "Surveillance camera feed lost", Label = "Security Issue" },
                new TicketDescription { Description = "POS malware detection", Label = "Security Incident" },
                new TicketDescription { Description = "Employee login sharing detected", Label = "Policy Violation" },
                new TicketDescription { Description = "Data breach of customer emails", Label = "Critical" },
                new TicketDescription { Description = "Night audit report generation failed", Label = "Reporting Issue" },
                new TicketDescription { Description = "Housekeeping status not updating", Label = "Workflow Issue" },
                new TicketDescription { Description = "Revenue management system pricing errors", Label = "Revenue Loss" },
                new TicketDescription { Description = "Staff shift trades not saving", Label = "Scheduling Issue" },
                new TicketDescription { Description = "Tip pooling calculations incorrect", Label = "Payroll Issue" },
                new TicketDescription { Description = "Employee discount not applying", Label = "HR System Issue" },
                new TicketDescription { Description = "Delivery window scheduling conflicts", Label = "Logistics Issue" },
                new TicketDescription { Description = "In-room TV streaming not working", Label = "AV Support" },
                new TicketDescription { Description = "Wi-Fi login portal broken", Label = "Network Issue" },
                new TicketDescription { Description = "Smart thermostat unresponsive", Label = "IoT Issue" },
                new TicketDescription { Description = "Mobile key not unlocking door", Label = "Security Issue" },
                new TicketDescription { Description = "Digital concierge chatbot down", Label = "AI Tool Issue" },
                new TicketDescription { Description = "QR code menu not loading", Label = "Customer Experience" },
                new TicketDescription { Description = "Waitlist app not notifying guests", Label = "Software Bug" },
                new TicketDescription { Description = "Online review kiosk frozen", Label = "Hardware Issue" },
                new TicketDescription { Description = "Digital shelf labels showing wrong prices", Label = "Pricing Error" },
                new TicketDescription { Description = "Kiosk for lottery/ATM offline", Label = "Revenue Loss" },
                new TicketDescription { Description = "Scanner not reading barcodes", Label = "Hardware Issue" },
                new TicketDescription { Description = "EMV chip reader declined valid cards", Label = "Payment Issue" },
                new TicketDescription { Description = "Self-checkout lane stuck in loop", Label = "Critical" },
                new TicketDescription { Description = "Digital coupons not applying", Label = "Promotion Error" },
                new TicketDescription { Description = "Scale not calibrating for produce", Label = "Hardware Issue" },
                new TicketDescription { Description = "Shelf tags not matching scanned prices", Label = "Pricing Error" },
                new TicketDescription { Description = "Auto-reorder system overstocking", Label = "Inventory Issue" },
                new TicketDescription { Description = "Expired items not flagged at POS", Label = "Compliance Issue" },
                new TicketDescription { Description = "Vendor EDI orders not processing", Label = "Integration Issue" },
                new TicketDescription { Description = "Discounts not applying for loyalty members", Label = "CRM Issue" },
                new TicketDescription { Description = "POS system crash during peak hours", Label = "Critical" },
                new TicketDescription { Description = "Split bill function not working", Label = "Software Bug" },
                new TicketDescription { Description = "Gratuity not auto-added for large parties", Label = "Policy Issue" },
                new TicketDescription { Description = "Menu price updates not syncing to POS", Label = "Data Sync Issue" },
                new TicketDescription { Description = "Tableside tablet orders not reaching kitchen", Label = "Integration Issue" },
                new TicketDescription { Description = "Ingredient stock levels inaccurate", Label = "Inventory Issue" },
                new TicketDescription { Description = "Recipe scaling errors in kitchen display", Label = "Software Bug" },
                new TicketDescription { Description = "Expired items not flagged in system", Label = "Compliance Issue" },
                new TicketDescription { Description = "Supplier CSV import failed", Label = "Data Issue" },
                new TicketDescription { Description = "Waste tracking not logging", Label = "Reporting Issue" },
                new TicketDescription { Description = "Online booking system down", Label = "Critical" },
                new TicketDescription { Description = "Duplicate room reservations", Label = "Data Error" },
                new TicketDescription { Description = "Overbooking due to sync failure", Label = "Revenue Loss" },
                new TicketDescription { Description = "OTA (Expedia/Booking.com) API connection lost", Label = "Integration Issue" },
                new TicketDescription { Description = "Group reservation not reflecting discounts", Label = "Pricing Error" },
                new TicketDescription { Description = "Check-in kiosk frozen", Label = "Hardware Issue" },
                new TicketDescription { Description = "Key card encoder not working", Label = "Critical" },
                new TicketDescription { Description = "Folio printing failed at checkout", Label = "Billing Issue" },
                new TicketDescription { Description = "Guest requests not logged in PMS", Label = "Workflow Issue" },
                new TicketDescription { Description = "Late checkout fee not auto-charged", Label = "Policy Issue" },
                new TicketDescription { Description = "Style guide repository access denied", Label = "Access Issue" },
                new TicketDescription { Description = "Editorial calendar sync conflicts", Label = "Collaboration Issue" },
                new TicketDescription { Description = "Writer laptop SSD failure", Label = "Hardware Issue" },
                new TicketDescription { Description = "Remote freelancer VPN issues", Label = "Remote Work" },
                new TicketDescription { Description = "Shared email inbox rules broken", Label = "Email Issue" },
                new TicketDescription { Description = "AP style checker tool offline", Label = "Editorial Tool" },
                new TicketDescription { Description = "Fact-checking database corrupted", Label = "Data Loss" },
                new TicketDescription { Description = "Editorial workflow approval stuck", Label = "Workflow Issue" },
                new TicketDescription { Description = "Writer productivity tracker crashing", Label = "Software Issue" },
                new TicketDescription { Description = "Cloud backup of 10-year archive failed", Label = "Critical" },
                new TicketDescription { Description = "Subscriber unable to access paid content", Label = "Revenue Issue" },
                new TicketDescription { Description = "Recurring payment failures", Label = "Payment Issue" },
                new TicketDescription { Description = "Gift subscription email not sending", Label = "Workflow Issue" },
                new TicketDescription { Description = "Paywall bypass detected", Label = "Security Issue" },
                new TicketDescription { Description = "Membership tier sync error", Label = "Data Issue" },
                new TicketDescription { Description = "Trial period not expiring", Label = "Revenue Issue" },
                new TicketDescription { Description = "Subscription analytics mismatch", Label = "Reporting Issue" },
                new TicketDescription { Description = "SSO not working for premium users", Label = "Authentication Issue" },
                new TicketDescription { Description = "Dynamic paywall not adapting", Label = "Personalization Issue" },
                new TicketDescription { Description = "Prorated refund calculation bug", Label = "Payment Issue" },
                new TicketDescription { Description = "Google Analytics data discrepancy", Label = "Reporting Issue" },
                new TicketDescription { Description = "Search console indexing errors", Label = "SEO Issue" },
                new TicketDescription { Description = "UTM tags not propagating in reports", Label = "Tracking Issue" },
                new TicketDescription { Description = "Heatmap tool not recording clicks", Label = "Analytics Issue" },
                new TicketDescription { Description = "Canonical URL misconfigurations", Label = "SEO Issue" },
                new TicketDescription { Description = "A/B test variant not serving", Label = "Testing Issue" },
                new TicketDescription { Description = "Keyword rank tracker API changes", Label = "SEO Issue" },
                new TicketDescription { Description = "Paywall analytics not capturing", Label = "Subscription Issue" },
                new TicketDescription { Description = "Dark traffic source misclassification", Label = "Analytics Issue" },
                new TicketDescription { Description = "Schema markup validation errors", Label = "SEO Issue" },
                new TicketDescription { Description = "Copyright check tool false negatives", Label = "Compliance Issue" },
                new TicketDescription { Description = "GDPR consent banners not logging", Label = "Legal Issue" },
                new TicketDescription { Description = "Missing alt text audit failure", Label = "Accessibility" },
                new TicketDescription { Description = "Plagiarism checker API downtime", Label = "Compliance Issue" },
                new TicketDescription { Description = "COPPA age gate not working", Label = "Legal Issue" },
                new TicketDescription { Description = "Takedown request not processed", Label = "Legal Issue" },
                new TicketDescription { Description = "Archive.org backup missing content", Label = "Compliance Issue" },
                new TicketDescription { Description = "Creative Commons attribution generator bug", Label = "Legal Issue" },
                new TicketDescription { Description = "Section 508 compliance checker errors", Label = "Accessibility" },
                new TicketDescription { Description = "Libel risk detection tool false alerts", Label = "Legal Issue" },
                new TicketDescription { Description = "Digital asset manager (DAM) search broken", Label = "Search Issue" },
                new TicketDescription { Description = "Stock photo API key expired", Label = "License Issue" },
                new TicketDescription { Description = "4K video rendering crashes Premiere", Label = "Performance Issue" },
                new TicketDescription { Description = "File naming convention violations", Label = "Policy Issue" },
                new TicketDescription { Description = "Deleted assets still in cache", Label = "Data Sync Issue" },
                new TicketDescription { Description = "Watermarked previews not generating", Label = "Automation Issue" },
                new TicketDescription { Description = "FTP transfer of large video files failing", Label = "Network Issue" },
                new TicketDescription { Description = "Asset metadata fields not saving", Label = "Data Issue" },
                new TicketDescription { Description = "Duplicate assets flooding repository", Label = "Storage Issue" },
                new TicketDescription { Description = "RAW photo files not previewing", Label = "Software Issue" },
                new TicketDescription { Description = "XML content not transforming to HTML", Label = "Publishing Issue" },
                new TicketDescription { Description = "Print-on-demand API connection timeout", Label = "API Issue" },
                new TicketDescription { Description = "ISBN assignment duplicates", Label = "Metadata Issue" },
                new TicketDescription { Description = "DRM-protected eBook not downloadable", Label = "Digital Publishing" },
                new TicketDescription { Description = "Print queue stuck at 99%", Label = "Hardware Issue" },
                new TicketDescription { Description = "Table of Contents auto-generation broken", Label = "Formatting Issue" },
                new TicketDescription { Description = "Watermarks missing from proofs", Label = "Prepress Issue" },
                new TicketDescription { Description = "Bulk ISBN registration CSV import failed", Label = "Data Issue" },
                new TicketDescription { Description = "Audiobook chapter timestamps misaligned", Label = "Audio Publishing" },
                new TicketDescription { Description = "Print run color consistency problems", Label = "Quality Control" },
                new TicketDescription { Description = "GPT-4 API quota exceeded", Label = "AI Tool Issue" },
                new TicketDescription { Description = "ChatGPT-generated content flagged as plagiarism", Label = "Compliance Issue" },
                new TicketDescription { Description = "AI image generator producing distorted outputs", Label = "AI Tool Issue" },
                new TicketDescription { Description = "Automated content scheduler stuck in loop", Label = "Workflow Issue" },
                new TicketDescription { Description = "Translation tool mistranslating key terms", Label = "Localization Issue" },
                new TicketDescription { Description = "Content scraping tool blocked by websites", Label = "Tool Issue" },
                new TicketDescription { Description = "AI voiceover mispronouncing names", Label = "Audio Content" },
                new TicketDescription { Description = "Automated fact-checker returning false positives", Label = "AI Tool Issue" },
                new TicketDescription { Description = "Hugging Face model not loading", Label = "AI Tool Issue" },
                new TicketDescription { Description = "AI content detector flagging human writing", Label = "Quality Issue" },
                new TicketDescription { Description = "InDesign file corruption", Label = "Critical" },
                new TicketDescription { Description = "Illustrator crashes when exporting SVG", Label = "Software Issue" },
                new TicketDescription { Description = "Canva team license assignment failed", Label = "License Issue" },
                new TicketDescription { Description = "Font licensing errors in PDF output", Label = "Compliance Issue" },
                new TicketDescription { Description = "High-res images not embedding in layout", Label = "Design Issue" },
                new TicketDescription { Description = "CMYK/PMS color mismatches in print", Label = "Prepress Issue" },
                new TicketDescription { Description = "EPUB validation errors", Label = "Digital Publishing" },
                new TicketDescription { Description = "Press-ready PDF rejected by printer", Label = "Prepress Issue" },
                new TicketDescription { Description = "Figma design system sync failure", Label = "Collaboration Issue" },
                new TicketDescription { Description = "Adobe Creative Cloud license limit reached", Label = "License Issue" },
                new TicketDescription { Description = "Google Docs edit permissions lost", Label = "Access Issue" },
                new TicketDescription { Description = "Track Changes not working in Word", Label = "Software Issue" },
                new TicketDescription { Description = "Shared Dropbox files missing", Label = "Data Sync Issue" },
                new TicketDescription { Description = "Grammarly plugin crashing Chrome", Label = "Plugin Issue" },
                new TicketDescription { Description = "Overleaf LaTeX compilation errors", Label = "Technical Writing" },
                new TicketDescription { Description = "Confluence page history corrupted", Label = "Data Loss" },
                new TicketDescription { Description = "Notion database export failures", Label = "Data Issue" },
                new TicketDescription { Description = "Zotero citation sync failure", Label = "Research Tool" },
                new TicketDescription { Description = "Version control conflicts in Git (for docs)", Label = "Collaboration Issue" },
                new TicketDescription { Description = "PDF comments not visible to team", Label = "Workflow Issue" },
                new TicketDescription { Description = "WordPress backend not loading", Label = "Critical" },
                new TicketDescription { Description = "Article drafts not saving in CMS", Label = "Data Loss" },
                new TicketDescription { Description = "Broken media uploads (images/videos)", Label = "CMS Issue" },
                new TicketDescription { Description = "Scheduled posts not publishing", Label = "Workflow Issue" },
                new TicketDescription { Description = "SEO plugin conflicts", Label = "Plugin Issue" },
                new TicketDescription { Description = "404 errors on published articles", Label = "CMS Issue" },
                new TicketDescription { Description = "User roles reset to default", Label = "Access Issue" },
                new TicketDescription { Description = "XML sitemap not updating", Label = "SEO Issue" },
                new TicketDescription { Description = "CMS update broke custom theme", Label = "Critical" },
                new TicketDescription { Description = "Multi-language content not syncing", Label = "Localization Issue" },
                new TicketDescription { Description = "Server room cooling failure", Label = "Critical" },
                new TicketDescription { Description = "UPS battery replacement needed", Label = "Maintenance" },
                new TicketDescription { Description = "Domain controller certificate expiring", Label = "Security Issue" },
                new TicketDescription { Description = "Scheduled patch deployment", Label = "Maintenance" },
                new TicketDescription { Description = "Backup verification alert", Label = "Backup Issue" },
                new TicketDescription { Description = "DNS resolution failures", Label = "Network Issue" },
                new TicketDescription { Description = "Email quota exceeded for staff", Label = "Storage Issue" },
                new TicketDescription { Description = "Spam flood in student mailboxes", Label = "Email Issue" },
                new TicketDescription { Description = "DHCP scope exhausted in dorm", Label = "Network Issue" },
                new TicketDescription { Description = "SSL certificate renewal for portal", Label = "Security Issue" },
                new TicketDescription { Description = "Student can’t print to lab printer", Label = "User Training" },
                new TicketDescription { Description = "Professor unable to share screen", Label = "User Training" },
                new TicketDescription { Description = "Forgot BitLocker recovery key", Label = "Authentication Issue" },
                new TicketDescription { Description = "Monitor resolution incorrect", Label = "Hardware Issue" },
                new TicketDescription { Description = "Mouse double-clicking randomly", Label = "Hardware Issue" },
                new TicketDescription { Description = "Keyboard not working in language lab", Label = "Hardware Issue" },
                new TicketDescription { Description = "Laptop overheating in class", Label = "Hardware Issue" },
                new TicketDescription { Description = "Tablet app icons rearranged", Label = "User Error" },
                new TicketDescription { Description = "Desktop shortcuts missing after update", Label = "User Error" },
                new TicketDescription { Description = "Student deleted important files", Label = "Data Recovery" },
                new TicketDescription { Description = "Student records corrupted", Label = "Critical" },
                new TicketDescription { Description = "Incorrect GPA calculations", Label = "Data Issue" },
                new TicketDescription { Description = "Attendance system not syncing", Label = "Data Sync Issue" },
                new TicketDescription { Description = "Financial aid report generation failed", Label = "Reporting Issue" },
                new TicketDescription { Description = "Duplicate student profiles in SIS", Label = "Data Issue" },
                new TicketDescription { Description = "Transcript PDF generation error", Label = "Reporting Issue" },
                new TicketDescription { Description = "Research data storage quota exceeded", Label = "Storage Issue" },
                new TicketDescription { Description = "BI dashboard showing outdated enrollment", Label = "Reporting Issue" },
                new TicketDescription { Description = "Library checkout system data loss", Label = "Critical" },
                new TicketDescription { Description = "Parent-teacher conference scheduler bug", Label = "Bug" },
                new TicketDescription { Description = "Lecture capture system audio missing", Label = "AV Support" },
                new TicketDescription { Description = "Live stream lagging for remote students", Label = "Performance Issue" },
                new TicketDescription { Description = "Conference mic echo in hybrid class", Label = "AV Support" },
                new TicketDescription { Description = "Panopto recordings not uploading", Label = "AV Support" },
                new TicketDescription { Description = "Smart podium touchscreen unresponsive", Label = "AV Support" },
                new TicketDescription { Description = "VR headset tracking failure", Label = "Lab Equipment" },
                new TicketDescription { Description = "Kaltura video playback errors", Label = "AV Support" },
                new TicketDescription { Description = "Live captioning not working", Label = "Accessibility" },
                new TicketDescription { Description = "Podcast studio mixer malfunction", Label = "AV Support" },
                new TicketDescription { Description = "Video conferencing blurry background", Label = "Software Issue" },
                new TicketDescription { Description = "Phishing email targeting students", Label = "Security Incident" },
                new TicketDescription { Description = "Unencrypted USB drive found", Label = "Security Issue" },
                new TicketDescription { Description = "FERPA data exposure risk", Label = "Compliance Issue" },
                new TicketDescription { Description = "Ransomware detection on lab PC", Label = "Security Incident" },
                new TicketDescription { Description = "Student hacking attempt detected", Label = "Security Incident" },
                new TicketDescription { Description = "Missing backups for research data", Label = "Backup Issue" },
                new TicketDescription { Description = "Unauthorized access to grading system", Label = "Security Incident" },
                new TicketDescription { Description = "Password policy too weak", Label = "Policy Issue" },
                new TicketDescription { Description = "Guest WiFi credentials leaked", Label = "Security Incident" },
                new TicketDescription { Description = "Firewall rule blocking STEM websites", Label = "Policy Issue" },
                new TicketDescription { Description = "MATLAB license expired", Label = "License Issue" },
                new TicketDescription { Description = "Adobe Creative Cloud install failing", Label = "Software Issue" },
                new TicketDescription { Description = "Exam software crashing on launch", Label = "Critical" },
                new TicketDescription { Description = "Outdated antivirus on lab PCs", Label = "Security Issue" },
                new TicketDescription { Description = "Python package installation blocked", Label = "Policy Issue" },
                new TicketDescription { Description = "Statistical software (SPSS) slow", Label = "Performance Issue" },
                new TicketDescription { Description = "CAD lab license shortage", Label = "License Issue" },
                new TicketDescription { Description = "Zoom recording permissions missing", Label = "Access Issue" },
                new TicketDescription { Description = "Windows update breaking legacy apps", Label = "Patch Issue" },
                new TicketDescription { Description = "iClicker software not detecting devices", Label = "Software Issue" },
                new TicketDescription { Description = "Student forgot password", Label = "Authentication Issue" },
                new TicketDescription { Description = "Faculty account locked out", Label = "Authentication Issue" },
                new TicketDescription { Description = "New staff account not provisioned", Label = "Account Setup" },
                new TicketDescription { Description = "Graduated student access not revoked", Label = "Access Issue" },
                new TicketDescription { Description = "Incorrect permissions on shared drive", Label = "Access Issue" },
                new TicketDescription { Description = "Email alias missing for department", Label = "Email Issue" },
                new TicketDescription { Description = "Active Directory sync failure", Label = "Critical" },
                new TicketDescription { Description = "Library system login failure", Label = "Authentication Issue" },
                new TicketDescription { Description = "Two-factor authentication not working", Label = "Security Issue" },
                new TicketDescription { Description = "Parent portal access denied", Label = "Access Issue" },
                new TicketDescription { Description = "Projector not displaying in Classroom 203", Label = "AV Support" },
                new TicketDescription { Description = "Computer lab printer jammed", Label = "Hardware Issue" },
                new TicketDescription { Description = "Student laptop charger broken", Label = "Hardware Issue" },
                new TicketDescription { Description = "Interactive whiteboard calibration off", Label = "AV Support" },
                new TicketDescription { Description = "Science lab sensors not connecting", Label = "IoT Issue" },
                new TicketDescription { Description = "Chromebooks not charging on cart", Label = "Hardware Issue" },
                new TicketDescription { Description = "3D printer filament error", Label = "Lab Equipment" },
                new TicketDescription { Description = "Microphone feedback in auditorium", Label = "AV Support" },
                new TicketDescription { Description = "Document camera frozen", Label = "AV Support" },
                new TicketDescription { Description = "Tablet stylus not responsive", Label = "Hardware Issue" },
                new TicketDescription { Description = "Wi-Fi down in Library", Label = "Critical" },
                new TicketDescription { Description = "Dormitory Ethernet ports inactive", Label = "Network Issue" },
                new TicketDescription { Description = "VPN not working for remote faculty", Label = "Remote Access Issue" },
                new TicketDescription { Description = "BYOD devices can’t connect to Eduroam", Label = "Network Issue" },
                new TicketDescription { Description = "Firewall blocking legitimate educational sites", Label = "Security Issue" },
                new TicketDescription { Description = "Slow internet in computer lab", Label = "Performance Issue" },
                new TicketDescription { Description = "IP conflict causing network drops", Label = "Network Issue" },
                new TicketDescription { Description = "Student portal timeout errors", Label = "Performance Issue" },
                new TicketDescription { Description = "Proxy server authentication failures", Label = "Authentication Issue" },
                new TicketDescription { Description = "Zoom/Teams calls dropping", Label = "VoIP Issue" },
                new TicketDescription { Description = "Moodle login page not loading", Label = "Critical" },
                new TicketDescription { Description = "Blackboard assignment submissions failing", Label = "Critical" },
                new TicketDescription { Description = "Canvas gradebook not syncing", Label = "Data Sync Issue" },
                new TicketDescription { Description = "Student unable to access course materials", Label = "Access Issue" },
                new TicketDescription { Description = "LMS outage during exams", Label = "Critical" },
                new TicketDescription { Description = "Discussion forum posts disappearing", Label = "Bug" },
                new TicketDescription { Description = "Slow loading of video lectures", Label = "Performance Issue" },
                new TicketDescription { Description = "Incorrect due dates on assignments", Label = "Data Issue" },
                new TicketDescription { Description = "LMS mobile app crashing on iOS", Label = "Mobile Issue" },
                new TicketDescription { Description = "Single Sign-On (SSO) failure", Label = "Authentication Issue" },
                new TicketDescription { Description = "Email server down company-wide", Label = "Critical" },
                new TicketDescription { Description = "SharePoint inaccessible", Label = "Critical" },
                new TicketDescription { Description = "ERP system performance degradation", Label = "Performance Issue" },
                new TicketDescription { Description = "Building access control system failure", Label = "Security Issue" },
                new TicketDescription { Description = "Payroll processing error", Label = "Critical" },
                new TicketDescription { Description = "Conference room projector bulb blown", Label = "AV Support" },
                new TicketDescription { Description = "Standing desk motor malfunction", Label = "Hardware Issue" },
                new TicketDescription { Description = "Docking station not charging laptop", Label = "Hardware Issue" },
                new TicketDescription { Description = "Keyboard spilled coffee damage", Label = "Hardware Issue" },
                new TicketDescription { Description = "IP phone display frozen", Label = "VoIP Issue" },
                new TicketDescription { Description = "Adobe Creative Cloud licensing error", Label = "License Issue" },
                new TicketDescription { Description = "Excel crashing with large datasets", Label = "Software Issue" },
                new TicketDescription { Description = "Outlook search not returning results", Label = "Email Issue" },
                new TicketDescription { Description = "Zoom virtual background not working", Label = "Software Issue" },
                new TicketDescription { Description = "CRM duplicate contact creation", Label = "Data Issue" },
                new TicketDescription { Description = "WiFi dead zone in west wing", Label = "Network Issue" },
                new TicketDescription { Description = "VPN connection drops when switching networks", Label = "Network Issue" },
                new TicketDescription { Description = "Printer offline after IP change", Label = "Network Issue" },
                new TicketDescription { Description = "Bandwidth throttling during backups", Label = "Performance Issue" },
                new TicketDescription { Description = "Guest WiFi portal broken", Label = "Network Issue" },
                new TicketDescription { Description = "Phishing email reported by multiple users", Label = "Security Incident" },
                new TicketDescription { Description = "Unencrypted laptop left in conference room", Label = "Security Incident" },
                new TicketDescription { Description = "Former employee still has Slack access", Label = "Access Issue" },
                new TicketDescription { Description = "Missing BitLocker recovery keys", Label = "Security Issue" },
                new TicketDescription { Description = "GDPR data subject access request", Label = "Compliance Issue" },
                new TicketDescription { Description = "Company iPhone stuck in recovery mode", Label = "Mobile Support" },
                new TicketDescription { Description = "Teams mobile app notification delay", Label = "Mobile Support" },
                new TicketDescription { Description = "Can't access network drives remotely", Label = "Access Issue" },
                new TicketDescription { Description = "Home office router configuration", Label = "Remote Support" },
                new TicketDescription { Description = "Dual-factor app not generating codes", Label = "Authentication Issue" },
                new TicketDescription { Description = "Design team font installation blocked", Label = "Policy Issue" },
                new TicketDescription { Description = "Engineering CAD license shortage", Label = "License Issue" },
                new TicketDescription { Description = "Marketing analytics dashboard timeout", Label = "Performance Issue" },
                new TicketDescription { Description = "Legal department secure file transfer", Label = "Security Issue" },
                new TicketDescription { Description = "HR onboarding checklist system error", Label = "Workflow Issue" },
                new TicketDescription { Description = "Digital signage stuck on boot screen", Label = "AV Support" },
                new TicketDescription { Description = "Cafeteria POS system offline", Label = "Critical" },
                new TicketDescription { Description = "Building directory touchscreen unresponsive", Label = "Hardware Issue" },
                new TicketDescription { Description = "EV charging station network error", Label = "IoT Issue" },
                new TicketDescription { Description = "Smart thermostat firmware update", Label = "IoT Issue" },
                new TicketDescription { Description = "Monitor resolution incorrect", Label = "Hardware Issue" },
                new TicketDescription { Description = "Mouse pointer jumps randomly", Label = "Hardware Issue" },
                new TicketDescription { Description = "Headset microphone static", Label = "Hardware Issue" },
                new TicketDescription { Description = "Windows update stuck at 32%", Label = "Software Issue" },
                new TicketDescription { Description = "Desktop shortcut icons missing", Label = "User Error" },
                new TicketDescription { Description = "Core banking system unresponsive", Label = "Critical" },
                new TicketDescription { Description = "ATM network outage", Label = "Critical" },
                new TicketDescription { Description = "Transaction processing delay", Label = "Critical" },
                new TicketDescription { Description = "SWIFT message failures", Label = "Critical" },
                new TicketDescription { Description = "Fraud detection system offline", Label = "Security Incident" },
                new TicketDescription { Description = "Teller unable to log into banking software", Label = "Authentication Issue" },
                new TicketDescription { Description = "Biometric scanner not working", Label = "Hardware Issue" },
                new TicketDescription { Description = "VPN access revoked for contractor", Label = "Access Issue" },
                new TicketDescription { Description = "Digital certificate expired for online banking", Label = "Security Issue" },
                new TicketDescription { Description = "RSA token not syncing", Label = "Authentication Issue" },
                new TicketDescription { Description = "Audit logs not being archived", Label = "Compliance Issue" },
                new TicketDescription { Description = "Unencrypted customer data detected", Label = "Security Incident" },
                new TicketDescription { Description = "FDIC compliance report generation failed", Label = "Reporting Issue" },
                new TicketDescription { Description = "Unauthorized access to loan database", Label = "Security Incident" },
                new TicketDescription { Description = "DLP alert: SSNs being emailed externally", Label = "Security Incident" },
                new TicketDescription { Description = "Teller printer jamming during peak hours", Label = "Hardware Issue" },
                new TicketDescription { Description = "Customer signature pad freezing", Label = "Hardware Issue" },
                new TicketDescription { Description = "Cash recycler calibration error", Label = "Hardware Issue" },
                new TicketDescription { Description = "Video surveillance system offline", Label = "Security Issue" },
                new TicketDescription { Description = "Loan application kiosk stuck on reboot", Label = "Hardware Issue" },
                new TicketDescription { Description = "Mobile check deposit failing", Label = "Mobile Banking Issue" },
                new TicketDescription { Description = "Online banking login captcha broken", Label = "Authentication Issue" },
                new TicketDescription { Description = "Zelle transfers not processing", Label = "Payment Issue" },
                new TicketDescription { Description = "eStatement PDF generation error", Label = "Reporting Issue" },
                new TicketDescription { Description = "Two-factor authentication SMS delays", Label = "Authentication Issue" },
                new TicketDescription { Description = "Trading floor latency spikes", Label = "Network Issue" },
                new TicketDescription { Description = "Data center cooling failure", Label = "Critical" },
                new TicketDescription { Description = "SAN storage at 95% capacity", Label = "Storage Issue" },
                new TicketDescription { Description = "BGP routing misconfiguration", Label = "Network Issue" },
                new TicketDescription { Description = "VoIP calls dropping in call center", Label = "VoIP Issue" },
                new TicketDescription { Description = "General ledger reconciliation error", Label = "Accounting System Issue" },
                new TicketDescription { Description = "Check imaging system blurry scans", Label = "Hardware Issue" },
                new TicketDescription { Description = "Wire transfer approval workflow stuck", Label = "Workflow Issue" },
                new TicketDescription { Description = "OFAC screening false positives", Label = "Compliance Issue" },
                new TicketDescription { Description = "Collateral management system crash", Label = "Critical" },
                new TicketDescription { Description = "Excel macros disabled in risk department", Label = "Policy Issue" },
                new TicketDescription { Description = "Bloomberg terminal login problems", Label = "Authentication Issue" },
                new TicketDescription { Description = "Dual monitors not working in trading", Label = "Hardware Issue" },
                new TicketDescription { Description = "Secure USB drives not recognized", Label = "Hardware Issue" },
                new TicketDescription { Description = "Keyboard wedge scanner malfunction", Label = "Hardware Issue" },
                new TicketDescription { Description = "DR failover test required", Label = "Maintenance" },
                new TicketDescription { Description = "Month-end batch job monitoring", Label = "Maintenance" },
                new TicketDescription { Description = "ATM software patch deployment", Label = "Maintenance" },
                new TicketDescription { Description = "Database index reorganization", Label = "Maintenance" },
                new TicketDescription { Description = "Firewall firmware upgrade", Label = "Maintenance" },
                new TicketDescription { Description = "Domain controller not responding", Label = "Critical" },
                new TicketDescription { Description = "Email server outage", Label = "Critical" },
                new TicketDescription { Description = "Active Directory sync failure", Label = "Critical" },
                new TicketDescription { Description = "Backup job failed", Label = "Critical" },
                new TicketDescription { Description = "Ransomware detection alert", Label = "Security Incident" },
                new TicketDescription { Description = "Whole network down", Label = "Critical" },
                new TicketDescription { Description = "Database corruption detected", Label = "Critical" },
                new TicketDescription { Description = "Storage array disk failure", Label = "Hardware Issue" },
                new TicketDescription { Description = "VPN connection drops intermittently", Label = "Network Issue" },
                new TicketDescription { Description = "WiFi authentication failures", Label = "Network Issue" },
                new TicketDescription { Description = "Printer queue jammed", Label = "Hardware Issue" },
                new TicketDescription { Description = "Monitor not displaying", Label = "Hardware Issue" },
                new TicketDescription { Description = "Keyboard/mouse not working", Label = "Hardware Issue" },
                new TicketDescription { Description = "Docking station issues", Label = "Hardware Issue" },
                new TicketDescription { Description = "Password reset required", Label = "Authentication Issue" },
                new TicketDescription { Description = "Multi-factor authentication not working", Label = "Authentication Issue" },
                new TicketDescription { Description = "Account locked out", Label = "Authentication Issue" },
                new TicketDescription { Description = "Certificate expired", Label = "Security Issue" },
                new TicketDescription { Description = "Firewall rule blocking legit traffic", Label = "Network Issue" },
                new TicketDescription { Description = "IP phone not registering", Label = "VoIP Issue" },
                new TicketDescription { Description = "Shared drive permissions incorrect", Label = "Access Issue" },
                new TicketDescription { Description = "Outlook search not working", Label = "Email Issue" },
                new TicketDescription { Description = "Calendar sync problems", Label = "Email Issue" },
                new TicketDescription { Description = "Teams meeting audio problems", Label = "Collaboration Issue" },
                new TicketDescription { Description = "SharePoint access denied", Label = "Access Issue" },
                new TicketDescription { Description = "BI report generation failing", Label = "Reporting Issue" },
                new TicketDescription { Description = "Windows update failing", Label = "Patch Issue" },
                new TicketDescription { Description = "Blue screen on startup", Label = "Hardware Issue" },
                new TicketDescription { Description = "Laptop fan extremely loud", Label = "Hardware Issue" },
                new TicketDescription { Description = "Battery not charging", Label = "Hardware Issue" },
                new TicketDescription { Description = "File server performance slow", Label = "Performance Issue" },
                new TicketDescription { Description = "Application timeout errors", Label = "Performance Issue" },
                new TicketDescription { Description = "High CPU usage alerts", Label = "Performance Issue" },
                new TicketDescription { Description = "Memory leaks detected", Label = "Performance Issue" },
                new TicketDescription { Description = "New employee onboarding", Label = "Account Setup" },
                new TicketDescription { Description = "Terminated employee offboarding", Label = "Account Setup" },
                new TicketDescription { Description = "Department move IT support", Label = "Logistics" },
                new TicketDescription { Description = "Conference room AV setup", Label = "AV Support" },
                new TicketDescription { Description = "Projector not detected", Label = "AV Support" },
                new TicketDescription { Description = "Microphone feedback issues", Label = "AV Support" },
                new TicketDescription { Description = "Mobile device enrollment", Label = "MDM Issue" },
                new TicketDescription { Description = "Kiosk mode configuration", Label = "MDM Issue" },
                new TicketDescription { Description = "Software license activation", Label = "License Issue" },
                new TicketDescription { Description = "Insufficient licenses available", Label = "License Issue" },
                new TicketDescription { Description = "Security policy compliance", Label = "Security Issue" },
                new TicketDescription { Description = "Unauthorized access alert", Label = "Security Issue" },
                new TicketDescription { Description = "Data recovery request", Label = "Backup Issue" },
                new TicketDescription { Description = "Tape backup failure", Label = "Backup Issue" },
                new TicketDescription { Description = "Cloud sync conflicts", Label = "Cloud Issue" },
                new TicketDescription { Description = "Application crash on startup", Label = "Critical Bug" },
                new TicketDescription { Description = "Database connection timeout", Label = "Critical Bug" },
                new TicketDescription { Description = "Payment processing failure", Label = "Critical Bug" },
                new TicketDescription { Description = "Login authentication failure", Label = "Authentication Issue" },
                new TicketDescription { Description = "SSO integration broken", Label = "Authentication Issue" },
                new TicketDescription { Description = "API rate limit exceeded", Label = "API Issue" },
                new TicketDescription { Description = "Webhook delivery failures", Label = "API Issue" },
                new TicketDescription { Description = "Mobile app freezing", Label = "Mobile Bug" },
                new TicketDescription { Description = "iOS build rejection", Label = "Mobile Bug" },
                new TicketDescription { Description = "Android crash reports", Label = "Mobile Bug" },
                new TicketDescription { Description = "UI rendering issues", Label = "Frontend Bug" },
                new TicketDescription { Description = "CSS layout broken", Label = "Frontend Bug" },
                new TicketDescription { Description = "Form validation errors", Label = "Frontend Bug" },
                new TicketDescription { Description = "Data export corruption", Label = "Backend Bug" },
                new TicketDescription { Description = "Incorrect calculations", Label = "Backend Bug" },
                new TicketDescription { Description = "Memory leak in service", Label = "Backend Bug" },
                new TicketDescription { Description = "Slow query performance", Label = "Database Issue" },
                new TicketDescription { Description = "Deadlock situations", Label = "Database Issue" },
                new TicketDescription { Description = "Migration script failure", Label = "Database Issue" },
                new TicketDescription { Description = "DevOps pipeline broken", Label = "CI/CD Issue" },
                new TicketDescription { Description = "Failed deployments", Label = "CI/CD Issue" },
                new TicketDescription { Description = "Container crashes", Label = "CI/CD Issue" },
                new TicketDescription { Description = "Kubernetes pod failures", Label = "CI/CD Issue" },
                new TicketDescription { Description = "Feature request: Dark mode", Label = "Enhancement" },
                new TicketDescription { Description = "Feature request: Export to PDF", Label = "Enhancement" },
                new TicketDescription { Description = "Documentation missing", Label = "Documentation" },
                new TicketDescription { Description = "Tutorial video request", Label = "Documentation" },
                new TicketDescription { Description = "Localization errors", Label = "Localization" },
                new TicketDescription { Description = "Timezone conversion bug", Label = "Localization" },
                new TicketDescription { Description = "Currency formatting issues", Label = "Localization" },
                new TicketDescription { Description = "Accessibility compliance", Label = "Accessibility" },
                new TicketDescription { Description = "Screen reader support", Label = "Accessibility" },
                new TicketDescription { Description = "Color contrast problems", Label = "Accessibility" },
                new TicketDescription { Description = "Integration failure with CRM", Label = "Integration" },
                new TicketDescription { Description = "ERP sync conflicts", Label = "Integration" },
                new TicketDescription { Description = "Third-party API changes", Label = "Integration" },
                new TicketDescription { Description = "Websocket disconnects", Label = "Realtime Issue" },
                new TicketDescription { Description = "Notification delays", Label = "Realtime Issue" },
                new TicketDescription { Description = "Session timeout too short", Label = "Configuration" },
                new TicketDescription { Description = "Password policy too strict", Label = "Configuration" },
                new TicketDescription { Description = "Audit log missing events", Label = "Security Issue" },
                new TicketDescription { Description = "XSS vulnerability found", Label = "Security Issue" },
                new TicketDescription { Description = "CSRF protection needed", Label = "Security Issue" },
                new TicketDescription { Description = "Pen test findings", Label = "Security Issue" },
                new TicketDescription { Description = "Load test failures", Label = "Performance" },
                new TicketDescription { Description = "Slow page loads", Label = "Performance" },
                new TicketDescription { Description = "Memory spikes", Label = "Performance" },
                new TicketDescription { Description = "Cache invalidation bug", Label = "Performance" },
                new TicketDescription { Description = "Search index corruption", Label = "Search Issue" },
                new TicketDescription { Description = "Incorrect search results", Label = "Search Issue" }
            };

            // Convert dataset to IDataView
            var dataView = _mlContext.Data.LoadFromEnumerable(descriptions);

            // Define the ML pipeline
            var pipeline = _mlContext.Transforms.Text.FeaturizeText("Features", nameof(TicketDescription.Description))
                .Append(_mlContext.Transforms.Conversion.MapValueToKey(inputColumnName: "Label", outputColumnName: "LabelKey"))
                .Append(_mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(labelColumnName: "LabelKey", featureColumnName: "Features"))
                .Append(_mlContext.Transforms.Conversion.MapKeyToValue(inputColumnName: "PredictedLabel", outputColumnName: "PredictedCategory"));

            // Train the model
            _model = pipeline.Fit(dataView);

            // Save the model for future use
            _mlContext.Model.Save(_model, dataView.Schema, "ticketClassificationModel.zip");
        }

        private void LoadModelIfExists()
        {
            if (File.Exists("ticketClassificationModel.zip"))
            {
                DataViewSchema modelSchema;
                _model = _mlContext.Model.Load("ticketClassificationModel.zip", out modelSchema);
                Console.WriteLine("Model loaded successfully.");
            }
            else
            {
                Console.WriteLine("Model file does not exist.");
            }
        }

        public string PredictTicketCategory(string ticketDescription)
        {
            // Load model if not already loaded
            if (_model == null)
            {
                LoadModelIfExists();
            }

            // If the model is still null, train the model
            if (_model == null)
            {
                TrainModel();
            }

            // Perform the prediction
            var predictionEngine = _mlContext.Model.CreatePredictionEngine<TicketDescription, TicketPrediction>(_model);
            var prediction = predictionEngine.Predict(new TicketDescription { Description = ticketDescription });

            // Debug log to check prediction result
            Console.WriteLine($"Predicted Category: {prediction.PredictedCategory}");
            return prediction.PredictedCategory;
        }
    }
}